"""Tool metadata — database names for citation attachment."""

from __future__ import annotations

# Minimal tool → database mapping (from planner TOOL_ROUTING)
TOOL_DATABASES: dict[str, str] = {
    "qptm_search": "qPTM",
    "qptm_site_conditions": "qPTM",
    "qptm_kinases": "qPTM",
    "iptmnet_enzymes": "iPTMnet",
    "iptmnet_ptm_ppi": "iPTMnet",
    "uniprot_annotation": "UniProt",
    "interpro_domains": "InterPro",
    "pfam_domains": "Pfam",
    "psp_kinase_substrate": "PhosphoSitePlus",
    "psp_regulatory": "PhosphoSitePlus",
    "psp_disease_sites": "PhosphoSitePlus",
    "psp_ptmvar": "PhosphoSitePlus",
    "dbptm_functional": "dbPTM",
    "ptm_stability": "PTM-stability",
    "activedriver_mutations": "ActiveDriverDB",
    "activedriver_kinase_network": "ActiveDriverDB",
    "pmads_drug_ptm": "PMADS",
    "drugbank_targets": "DrugBank",
    "weram_regulators": "WERAM",
    "ubibrowser_interactions": "UbiBrowser",
    "gpsuber_e3_sites": "GPS-Uber",
    "gps6_kinases": "GPS 6.0",
    "gpssumo2_sites": "GPS-SUMO 2.0",
    "kaka_kinase_mutations": "KAKA",
    "ekpi_kinases": "eKPI",
    "ekpi_quantitative": "eKPI",
    "ptmphase_llps": "PTMPhaSe",
    "dscope_literature": "dSCOPE",
    "dscope_predictions": "dSCOPE",
    "ptmd_disease": "PTMD",
    "cancerproteome_disease": "CancerProteome",
    "ptmint_ppi": "PTMint",
    "string_ppi": "STRING",
    "biogrid_interactions": "BioGRID",
    "intact_interactions": "IntAct",
    "reactome_pathways": "Reactome",
    "kegg_pathways": "KEGG",
    "pathbank_pathways": "PathBank",
    "ptmcode_associations": "PTMcode2",
    "inuloc_nls_nes": "iNuLoC",
    "inuloc_nuclear_prob": "iNuLoC",
    "funcscore_phosphosite": "Funcscore",
    "decryptm_drug_ptm": "decryptM",
    "compartments_localization": "COMPARTMENTS",
    "subcell_scsi": "SubCELL",
    "signalp_prediction": "SignalP",
    "pubtator_literature_search": "PubTator3",
    "pubmed_esearch": "PubMed",
    "europepmc_literature_search": "Europe PMC",
    "pubmed_fetch_abstracts": "PubMed",
    "pubmed_fetch_fulltext": "Europe PMC",
}


def tool_database(tool_name: str) -> str:
    return TOOL_DATABASES.get(tool_name, tool_name)
